#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

CACHE_DIR="${CACHE_DIR:-./cache}"
MODEL="${MODEL:-meta-llama/Llama-2-7b-hf}"
BITS="${BITS:-3}"
DATASET="${DATASET:-redpajama}"
SEQ_LEN="${SEQ_LEN:-4096}"
NUM_EXAMPLES="${NUM_EXAMPLES:-1024}"
REDPAJAMA_SOURCE="${REDPAJAMA_SOURCE:-cache}"
REDPAJAMA_DATASET_REPO="${REDPAJAMA_DATASET_REPO:-togethercomputer/RedPajama-Data-1T}"
RESULTS_DIR="${RESULTS_DIR:-./results/ppl}"
PPL_DATASETS="${PPL_DATASETS:-wikitext2,c4}"
PIPELINE_MODE="${PIPELINE_MODE:-quantize}"
RUN_POST_QUANT_PPL="${RUN_POST_QUANT_PPL:-1}"

BETA="${BETA:-0}"
RANK="${RANK:-4}"
NUM_OUTPUT_GROUPS="${NUM_OUTPUT_GROUPS:-8}"
CALIBRATION_BATCH_SIZE="${CALIBRATION_BATCH_SIZE:-1}"
FISHER_PROBES="${FISHER_PROBES:-16}"
GRADIENT_NUM_EXAMPLES="${GRADIENT_NUM_EXAMPLES:-}"
STATS_LAYER_CHUNK_SIZE="${STATS_LAYER_CHUNK_SIZE:-8}"
MAX_OUTER_ITERS="${MAX_OUTER_ITERS:-8}"
REL_TOL="${REL_TOL:-1e-7}"
LAMBDA_SAFETY="${LAMBDA_SAFETY:-1.01}"
TIE_TOL="${TIE_TOL:-0.0}"
CPU_COUNT="${CPU_COUNT:-}"

export CACHE_DIR MODEL BITS DATASET SEQ_LEN NUM_EXAMPLES REDPAJAMA_SOURCE
export REDPAJAMA_DATASET_REPO RESULTS_DIR PPL_DATASETS PIPELINE_MODE RUN_POST_QUANT_PPL
export BETA RANK NUM_OUTPUT_GROUPS CALIBRATION_BATCH_SIZE FISHER_PROBES
export GRADIENT_NUM_EXAMPLES STATS_LAYER_CHUNK_SIZE MAX_OUTER_ITERS REL_TOL
export LAMBDA_SAFETY TIE_TOL CPU_COUNT

bash "${SCRIPT_DIR}/ensure_endloss_dlr_base.sh"